services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      APP_NAME: Bookdrop
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:PjShUffb330Gr0swAYSUxRi/7KDasmVqyBjsRh7m8l8=
      APP_URL: http://localhost:8080
      BOOKDROP_PUBLIC_BASE_URL: http://localhost:8080
      LOG_CHANNEL: stderr
      DB_CONNECTION: sqlite
      DB_DATABASE: /data/database.sqlite
      BOOKDROP_STORAGE_PATH: /data
      BOOKDROP_BOOKS_PATH: books
      SESSION_DRIVER: database
      CACHE_STORE: database
      QUEUE_CONNECTION: database
    volumes:
      - bookdrop-data:/data

volumes:
  bookdrop-data:
